"""Tests for the dependency detector: real osv-scanner subprocess
calls (not mocked — see plans/008-dependency-skill.md's kickoff note
on why), result-to-finding mapping, schema conformance, and error
handling.

Fixtures under testdata/ are REAL lockfiles generated by the actual
package managers (npm install, go get), not hand-typed approximations
— a hand-crafted package-lock.json was found at kickoff to behave
differently from a real one in some cases, so only real,
tool-generated fixtures are used here.

Requires the real `osv-scanner` CLI on PATH and network access to
query OSV. Run with: python3 -m unittest test_scanner -v (from inside
detectors/dependency/).
"""

from __future__ import annotations

import io
import json
import shutil
import sys
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path
from unittest import mock

import scanner
from scanner import ScannerError

DETECTOR_DIR = Path(__file__).parent
SECURITY_SKILL_DIR = next(p for p in DETECTOR_DIR.resolve().parents if (p / "common").is_dir())
SCHEMA_DIR = SECURITY_SKILL_DIR / "schema"
TESTDATA = DETECTOR_DIR / "testdata"

sys.path.insert(0, str(SECURITY_SKILL_DIR / "common"))
from schema_validation import validate_against_schema  # noqa: E402

sys.path.insert(0, str(SECURITY_SKILL_DIR / "knowledge"))
import standards  # noqa: E402


def _osv_scanner_available() -> bool:
    return shutil.which("osv-scanner") is not None


@unittest.skipUnless(_osv_scanner_available(), "requires the real osv-scanner CLI on PATH")
class PerClassDetectionTests(unittest.TestCase):
    """Real osv-scanner subprocess calls against real, tool-generated
    lockfiles — mirrors detectors/code-review's per-class detection
    tests, for a wrapped external tool instead of an in-process one."""

    def test_finds_cve_in_real_npm_lockfile(self) -> None:
        findings = scanner.scan_paths([str(TESTDATA / "npm-vulnerable")])
        self.assertTrue(any(f["ruleId"] == "dependency.cve" for f in findings), findings)
        for f in findings:
            self.assertEqual(f["subSkill"], "dependency")
            self.assertEqual(f["artifactType"], "package-lock")

    def test_clean_lockfile_produces_no_findings(self) -> None:
        findings = scanner.scan_paths([str(TESTDATA / "npm-clean")])
        self.assertEqual(findings, [])

    def test_finds_deprecated_package_in_real_npm_lockfile(self) -> None:
        findings = scanner.scan_paths([str(TESTDATA / "npm-deprecated")])
        deprecated = [f for f in findings if f["ruleId"] == "dependency.deprecated-package"]
        self.assertTrue(deprecated, findings)
        for f in deprecated:
            self.assertEqual(f["confidence"], scanner._DEPRECATED_CONFIDENCE)

    def test_finds_malicious_package(self) -> None:
        findings = scanner.scan_paths([str(TESTDATA / "npm-malicious")])
        malicious = [f for f in findings if f["ruleId"] == "dependency.malicious-package"]
        self.assertTrue(malicious, findings)
        for f in malicious:
            self.assertEqual(f["severity"], "Critical")

    def test_corrupted_lockfile_alongside_valid_one_does_not_discard_good_results(self) -> None:
        # Verified for real during the "test plan 008" round: a
        # syntactically-broken package-lock.json in one subdirectory
        # doesn't prevent osv-scanner from still reporting a valid
        # sibling lockfile's real findings — mirrors 007's
        # partial-parse-failure discipline, confirmed here rather than
        # assumed to carry over from a different tool.
        findings = scanner.scan_paths([str(TESTDATA / "mixed-with-corrupted")])
        self.assertTrue(any(f["ruleId"] == "dependency.cve" for f in findings), findings)

    def test_finds_lockfile_nested_in_a_subdirectory(self) -> None:
        # Found during the "test plan 008" round: scanning a repo root
        # whose lockfile lives one directory down (an extremely common
        # real layout, e.g. a backend/ subfolder) silently found
        # nothing without --recursive — a false "no vulnerabilities"
        # rather than a crash. testdata/nested-repo/backend/ holds the
        # same vulnerable lockfile as npm-vulnerable/, one level deeper.
        findings = scanner.scan_paths([str(TESTDATA / "nested-repo")])
        self.assertTrue(any(f["ruleId"] == "dependency.cve" for f in findings), findings)

    def test_finds_license_violation_against_permissive_only_default(self) -> None:
        # npm-malicious's fixture package has no declared license,
        # which trips the default permissive-only allowlist.
        findings = scanner.scan_paths([str(TESTDATA / "npm-malicious")])
        self.assertTrue(any(f["ruleId"] == "dependency.license-violation" for f in findings), findings)

    def test_finds_cve_in_real_go_module(self) -> None:
        findings = scanner.scan_paths([str(TESTDATA / "go-vulnerable")])
        self.assertTrue(any(f["ruleId"] == "dependency.cve" for f in findings), findings)

    def test_finds_cve_in_real_pypi_requirements(self) -> None:
        findings = scanner.scan_paths([str(TESTDATA / "pypi-vulnerable")])
        self.assertTrue(any(f["ruleId"] == "dependency.cve" for f in findings), findings)


@unittest.skipUnless(_osv_scanner_available(), "requires the real osv-scanner CLI on PATH")
class SchemaConformanceTests(unittest.TestCase):
    def test_real_findings_validate_against_finding_schema(self) -> None:
        schema = json.loads((SCHEMA_DIR / "finding.schema.json").read_text(encoding="utf-8"))
        findings = scanner.scan_paths([str(TESTDATA / "npm-deprecated")])
        findings += scanner.scan_paths([str(TESTDATA / "npm-malicious")])
        self.assertGreaterEqual(len(findings), 3, "expected CVE + deprecated + malicious + license findings")
        seen_rule_ids = set()
        for f in findings:
            errors = validate_against_schema(schema, f)
            self.assertEqual(errors, [], f"{f['ruleId']} finding is not schema-valid: {errors}")
            seen_rule_ids.add(f["ruleId"])
        self.assertEqual(
            seen_rule_ids,
            {"dependency.cve", "dependency.deprecated-package", "dependency.malicious-package", "dependency.license-violation"},
            "expected to exercise schema conformance for all four finding types",
        )


@unittest.skipUnless(_osv_scanner_available(), "requires the real osv-scanner CLI on PATH")
class ErrorHandlingTests(unittest.TestCase):
    def test_bad_path_raises_scanner_error(self) -> None:
        with self.assertRaises(ScannerError):
            scanner.scan_paths(["/tmp/definitely-does-not-exist-008.lock"])

    def test_returncode_outside_0_1_raises_even_with_valid_json_stdout(self) -> None:
        # Real osv-scanner behavior for a bad path (verified at
        # implementation): rc=127 with *empty* stdout, so the test
        # above technically passes via the JSON-parse-failure path,
        # not the returncode check itself — that's a test-quality gap
        # of the exact shape 006/007 already caught once each. Isolate
        # the returncode check specifically by mocking subprocess.run
        # to return valid JSON alongside a bad code.
        fake_proc = mock.Mock(returncode=127, stdout='{"results": []}', stderr="mocked failure")
        with mock.patch("scanner.subprocess.run", return_value=fake_proc):
            with self.assertRaises(ScannerError):
                scanner.run_osv_scanner(["irrelevant"])

    def test_missing_osv_scanner_binary_raises_actionable_error(self) -> None:
        with mock.patch("scanner.shutil.which", return_value=None):
            with self.assertRaises(ScannerError) as ctx:
                scanner.run_osv_scanner(["irrelevant"])
        self.assertIn("go install", str(ctx.exception))

    def test_directory_with_no_lockfile_produces_no_findings_not_an_error(self) -> None:
        # --allow-no-lockfiles is always passed — a directory genuinely
        # having no dependencies must not be treated as a scan failure.
        with tempfile.TemporaryDirectory() as tmp:
            findings = scanner.scan_paths([tmp])
        self.assertEqual(findings, [])


class MappingTests(unittest.TestCase):
    """Pure-function unit tests for the result-to-finding mapping — no
    osv-scanner subprocess needed, fast and deterministic."""

    def test_cvss_score_bands_match_official_scale(self) -> None:
        # Verified against first.org/cvss/v3-1/specification-document
        # Table 14 at implementation, not guessed.
        self.assertEqual(scanner._severity_from_cvss_score(9.8), "Critical")
        self.assertEqual(scanner._severity_from_cvss_score(9.0), "Critical")
        self.assertEqual(scanner._severity_from_cvss_score(8.9), "High")
        self.assertEqual(scanner._severity_from_cvss_score(7.0), "High")
        self.assertEqual(scanner._severity_from_cvss_score(6.9), "Medium")
        self.assertEqual(scanner._severity_from_cvss_score(4.0), "Medium")
        self.assertEqual(scanner._severity_from_cvss_score(3.9), "Low")
        self.assertEqual(scanner._severity_from_cvss_score(0.1), "Low")
        self.assertEqual(scanner._severity_from_cvss_score(0.0), "Info")

    def test_vuln_severity_prefers_qualitative_database_specific(self) -> None:
        vuln = {"database_specific": {"severity": "HIGH"}}
        self.assertEqual(scanner._vuln_severity(vuln, group_max_severity="1.0"), "High")

    def test_vuln_severity_falls_back_to_group_cvss_score(self) -> None:
        vuln = {"database_specific": {}}
        self.assertEqual(scanner._vuln_severity(vuln, group_max_severity="9.5"), "Critical")

    def test_vuln_severity_defaults_to_medium_when_nothing_available(self) -> None:
        self.assertEqual(scanner._vuln_severity({"database_specific": {}}, group_max_severity=None), "Medium")

    def test_cve_confidence_higher_when_github_reviewed(self) -> None:
        reviewed = {"database_specific": {"github_reviewed": True}}
        unreviewed = {"database_specific": {"github_reviewed": False}}
        self.assertGreater(scanner._cve_confidence(reviewed), scanner._cve_confidence(unreviewed))

    def test_cve_references_use_specific_cwe_when_present(self) -> None:
        vuln = {"database_specific": {"cwe_ids": ["CWE-79"]}}
        refs = scanner._cve_references(vuln)
        self.assertIn({"standard": "CWE", "id": "CWE-79"}, refs)
        self.assertIn({"standard": "OWASP-Top10", "id": "A03:2025"}, refs)

    def test_cve_references_fall_back_to_generic_cwe_when_absent(self) -> None:
        vuln = {"database_specific": {}}
        refs = scanner._cve_references(vuln)
        self.assertIn({"standard": "CWE", "id": "CWE-1395"}, refs)

    def test_cve_references_drop_unrecognized_cwe(self) -> None:
        vuln = {"database_specific": {"cwe_ids": ["CWE-999999"]}}
        refs = scanner._cve_references(vuln)
        self.assertNotIn({"standard": "CWE", "id": "CWE-999999"}, refs)
        # Falls back to the generic reference since nothing else resolved.
        self.assertIn({"standard": "CWE", "id": "CWE-1395"}, refs)


class FindingIdTests(unittest.TestCase):
    def test_deterministic_for_identical_input(self) -> None:
        a = scanner._finding_id("dependency.cve", "lock.json", "pkg", "1.0.0", "CVE-2020-1")
        b = scanner._finding_id("dependency.cve", "lock.json", "pkg", "1.0.0", "CVE-2020-1")
        self.assertEqual(a, b)

    def test_distinct_vulnerabilities_on_the_same_package_get_distinct_ids(self) -> None:
        # Same rule, same file, same package/version — only the
        # specific vulnerability id differs (e.g. two CVEs for one
        # package version). Mirrors the same-line-distinct-byte-offset
        # discipline from 006/007's findingId regression tests.
        a = scanner._finding_id("dependency.cve", "lock.json", "pkg", "1.0.0", "CVE-2020-1")
        b = scanner._finding_id("dependency.cve", "lock.json", "pkg", "1.0.0", "CVE-2020-2")
        self.assertNotEqual(a, b)


class ConsistencyTests(unittest.TestCase):
    def test_expected_cwe_ids_resolve_in_knowledge_base(self) -> None:
        for cwe_id in ("CWE-506", "CWE-1104", "CWE-1395"):
            self.assertTrue(standards.exists("CWE", cwe_id), cwe_id)

    def test_expected_owasp_top10_2025_id_resolves(self) -> None:
        self.assertTrue(standards.exists("OWASP-Top10", "A03:2025"))


@unittest.skipUnless(_osv_scanner_available(), "requires the real osv-scanner CLI on PATH")
class MainCliTests(unittest.TestCase):
    def test_prints_findings_as_json_and_returns_0(self) -> None:
        out = io.StringIO()
        with redirect_stdout(out):
            code = scanner.main([str(TESTDATA / "npm-vulnerable")])
        self.assertEqual(code, 0)
        parsed = json.loads(out.getvalue())
        self.assertGreaterEqual(len(parsed), 1)

    def test_bad_path_returns_1_and_prints_error(self) -> None:
        err = io.StringIO()
        with redirect_stdout(io.StringIO()), redirect_stderr(err):
            code = scanner.main(["/tmp/definitely-does-not-exist-008.lock"])
        self.assertEqual(code, 1)
        self.assertIn("SCANNER ERROR", err.getvalue())


class CrossPlatformEncodingTests(unittest.TestCase):
    def test_round_trip_non_ascii_content_with_explicit_utf8(self) -> None:
        text = "em dash — and middle dot · round-trip"
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "roundtrip.txt"
            path.write_text(text, encoding="utf-8")
            self.assertEqual(path.read_text(encoding="utf-8"), text)


class SourceEncodingAuditTests(unittest.TestCase):
    def test_no_read_or_write_text_call_omits_encoding(self) -> None:
        import ast

        violations = []
        for path in sorted(DETECTOR_DIR.glob("*.py")):
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
            for node in ast.walk(tree):
                if (
                    isinstance(node, ast.Call)
                    and isinstance(node.func, ast.Attribute)
                    and node.func.attr in ("read_text", "write_text")
                ):
                    kwarg_names = {kw.arg for kw in node.keywords}
                    if "encoding" not in kwarg_names:
                        violations.append(f"{path.name}:{node.lineno} .{node.func.attr}() missing encoding=")
        self.assertEqual(violations, [])


if __name__ == "__main__":
    unittest.main()
